### ISSUE TITLE
Project Proposal Feedback

### ISSUE THREAD

**Issue by PhilChodrow** [panxinming/PIC16B-Proposal#1]
Hi Xinming and Xinyu, 

This looks like a very interesting proposal! You've clearly thought through your ideas, and I look forward to seeing what you produce. 

There are two things that I would like you to revise before I give you credit on this assignment. 

1. First, regarding your tools and skills. While it's true that there are many tools that might accomplish your tasks well, **this is a Python class**. So, while I won't prevent you from using things like R or Tableau, I can give you credit only on the components of your project that are implemented in Python. Because of this, I strongly recommend that you plan to implement as many components in Python as possible. I expect that you will in fact be able to implement your entire project in Python (e.g. data cleaning with Pandas, visualization with Plotly). Please use your judgment, and keep in mind that I need to see "one project's worth" of Python code in order to give you credit. You should revise your proposal to be clearer about exactly which components you will implement in Python. 
2. Regarding ethics, I would like you to include a discussion of the following questions: 
  - Suppose that someone uses your app and it says that they have a low risk. Because of this, they don't go to the doctor for a checkup -- but later, they develop breast cancer. Is your app responsible for this outcome? Why or why not? 
  - It is often found that medical recommender algorithms can work well on some groups of people and not others. For example, here is a [summary of a recent journal article](https://publichealth.berkeley.edu/news-media/research-highlights/ziad-obermeyer-and-colleagues-at-the-booth-school-of-business-release-health-care-algorithmic-bias-playbook/) in which a recommender system included racial bias. Is there a risk of such bias in your algorithm? How do you know? Is there anything you might be able to do to check? 

Once you have made revisions on these two components, please let me know by replying to this issue. I'll then reassess your proposal for credit. 

I'm excited to see what you create!

**Comment by panxinming** [comment]
Hi, Professor. Can you check our revised proposal? Thank you.

**Comment by panxinming** [comment]
> Hi Xinming and Xinyu,
> 
> This looks like a very interesting proposal! You've clearly thought through your ideas, and I look forward to seeing what you produce.
> 
> There are two things that I would like you to revise before I give you credit on this assignment.
> 
> 1. First, regarding your tools and skills. While it's true that there are many tools that might accomplish your tasks well, **this is a Python class**. So, while I won't prevent you from using things like R or Tableau, I can give you credit only on the components of your project that are implemented in Python. Because of this, I strongly recommend that you plan to implement as many components in Python as possible. I expect that you will in fact be able to implement your entire project in Python (e.g. data cleaning with Pandas, visualization with Plotly). Please use your judgment, and keep in mind that I need to see "one project's worth" of Python code in order to give you credit. You should revise your proposal to be clearer about exactly which components you will implement in Python.
> 2. Regarding ethics, I would like you to include a discussion of the following questions:
> 
> * Suppose that someone uses your app and it says that they have a low risk. Because of this, they don't go to the doctor for a checkup -- but later, they develop breast cancer. Is your app responsible for this outcome? Why or why not?
> * It is often found that medical recommender algorithms can work well on some groups of people and not others. For example, here is a [summary of a recent journal article](https://publichealth.berkeley.edu/news-media/research-highlights/ziad-obermeyer-and-colleagues-at-the-booth-school-of-business-release-health-care-algorithmic-bias-playbook/) in which a recommender system included racial bias. Is there a risk of such bias in your algorithm? How do you know? Is there anything you might be able to do to check?
> 
> Once you have made revisions on these two components, please let me know by replying to this issue. I'll then reassess your proposal for credit.
> 
> I'm excited to see what you create!

**Comment by PhilChodrow** [comment]
Nice revisions! You have received credit for this assignment.
